sources:
  - glyphs/Onest-Black.glyphs
  - glyphs/Onest-Bold.glyphs
  - glyphs/Onest-ExtraBold.glyphs
  - glyphs/Onest-Light.glyphs
  - glyphs/Onest-Medium.glyphs
  - glyphs/Onest-Regular.glyphs
  - glyphs/Onest-Thin.glyphs
familyName: Onest
outputDir: "../fonts"
